name: "Python Package Release"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
#  push:
#    branches:
#      - tasklist-issue-3005

jobs:
  trigger-release:
    runs-on: ubuntu-latest




